# Generated by Django 4.1 on 2024-12-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="producto",
            name="etiqueta",
            field=models.ManyToManyField(related_name="productos", to="myapp.etiqueta"),
        ),
    ]
