# Generated by Django 4.1 on 2024-12-04 00:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_producto_stock_alter_producto_etiqueta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="nonbre",
            new_name="nombre",
        ),
    ]
