# Generated by Django 4.1 on 2024-12-04 00:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
    ]
